#238 Configuring FMCard
HZN-one/flex pull request #19
Opened 2021-12-28 01:44 UTC by pranotoism

2021-12-28 01:53 UTC, didikmulyadi commented on .github/workflows/chromatic.yml
> +      - run: yarn
why we need yarn here?

2021-12-28 03:26 UTC, gilangdarmawan requested changes

2021-12-28 03:26 UTC, gilangdarmawan commented on src/Components/Molecules/FMCard/index.tsx
> +        {props.children ? (
just check if there's any content or not.

2021-12-28 03:26 UTC, gilangdarmawan commented on src/Components/Molecules/FMCard/index.tsx
> +            HZN FLEX CARD
i think we can change this default `HZN FLEX CARD` value or remove it if we didn't use it.

2021-12-29 00:56 UTC, gilangdarmawan approved these changes

2021-12-29 02:00 UTC, merged