#630/fl settings navbar layout
HZN-one/flex pull request #22
Opened 2022-01-10 02:48 UTC by pranotoism

## Thanks for your support to the project. Please check below mentioned points -

### Detailed description of changes

...

### Recommendations on how to test the changes

...

### Checklist for developer

- [ ] The code builds clean without any errors or warnings
- [ ] The code does not contain commented out code
- [ ] The code does not log anything to console
- [ ] I have added unit test(s) to cover new code and successfully executed ran it
- [ ] I have thoroughly tested the new code and any adjacent features it may affect

### Link to related issue(s)

...

### Screenshots or videos (before and after if appropriate)

#### Before

...

#### After

...

2022-01-10 08:04 UTC, ardiwine commented
@pranotoism tolong di check checklist yang dibuat sama rika di description PR nya. pastiin itu semua sudah di kerjain, dan tolong di check masing2 boxnya kalau memang sudah .

2022-01-10 08:06 UTC, ardiwine commented
@pranotoism component testing nya belum ada?

2022-01-10 10:01 UTC, gilangdarmawan requested changes

2022-01-10 11:19 UTC, pranotoism commented on src/Components/Atoms/FAOutlinedInput/index.tsx
> +import { InputLabel } from "@mui/material";
done

2022-01-10 14:39 UTC, pranotoism commented on src/Components/Organisms/FOHeader/FOHeader.interfaces.tsx
> +  open?: boolean;
im gonna stick to the original as the MUI guide just to make it clean and simple

2022-01-10 14:39 UTC, pranotoism commented on src/Components/Atoms/FAInput/FAInput.interfaces.tsx
> +  error?: boolean;
im gonna stick to the original as the MUI guide just to make it clean and simple

2022-01-11 01:02 UTC, gilangdarmawan approved these changes

2022-01-11 02:47 UTC, merged