#206 Molekul - FMSearch
HZN-one/flex pull request #37
Opened 2022-02-15 06:40 UTC by bryantobing12

## Thanks for your support to the project. Please check below mentioned points -

### Detailed description of changes

- Outlined Input border radius set to 8px
- Search icon adornment to use primary color
- Storybook example

### Recommendations on how to test the changes

- Check if the component match the design

### Checklist for developer

- [ ] The code builds clean without any errors or warnings
- [ ] The code does not contain commented out code
- [ ] The code does not log anything to console
- [ ] I have added unit test(s) to cover new code and successfully executed ran it
- [ ] I have thoroughly tested the new code and any adjacent features it may affect

### Link to related issue(s)

https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/206

### Screenshots or videos (before and after if appropriate)

#### Before

N / A

#### After

![image](https://user-images.githubusercontent.com/46083126/154006647-434b35e2-548b-43e0-bcd1-1c5295c9b0c7.png)

2022-02-15 08:54 UTC, muhammad-farhan64 commented on src/Components/Molecules/FMSearch/index.tsx
>        }}
ini mungkin bisa di ganti dengan adorment dan adormentPosiition propsnya

2022-02-16 01:42 UTC, bryantobing12 commented on src/Components/Molecules/FMSearch/index.tsx
>        }}
updated @muhammad-farhan64

2022-02-16 03:45 UTC, gilangdarmawan requested changes

2022-02-16 03:45 UTC, gilangdarmawan commented on src/Components/Molecules/FMSearch/FMSearch.interfaces.tsx
> +  sx?: StandardTextFieldProps["sx"];
ada concern kenapa add `sx`? soalnya di component nya sx ga dipake

2022-02-16 03:45 UTC, gilangdarmawan commented on src/Components/Molecules/FMSearch/index.tsx
> +            <SearchIcon color="primary"></SearchIcon>
Bisa pakai `FAIcon` sebagai alternatif

2022-02-16 03:45 UTC, gilangdarmawan commented on src/Components/Molecules/FMSearch/index.tsx
> +    <div data-testid={testID}>
Boleh diganti ke `<Box>`

2022-02-16 03:48 UTC, bryantobing12 commented on src/Components/Molecules/FMSearch/FMSearch.interfaces.tsx
> +  sx?: StandardTextFieldProps["sx"];
di `FOHeader` FMSearch nya make `sx` . tapi ini juga yang seharusnya ga boleh sih karena dicustom inline gitu. 
![image](https://user-images.githubusercontent.com/46083126/154192514-dd64fc91-5e32-4e05-bac8-ff289f9a1391.png)

2022-02-16 04:44 UTC, gilangdarmawan approved these changes

2022-02-16 04:47 UTC, merged