Add Feature Expand and collapse in FMCARD
HZN-one/flex pull request #46
Opened 2022-02-17 11:03 UTC by muhammad-farhan64

## Thanks for your support to the project. Please check below mentioned points -

### Detailed description of changes

1. add feature expand and collapse in FMCARD
### Recommendations on how to test the changes

1. go to storybook
2.  set isCollapseAble true

### Checklist for developer

- [ ] The code builds clean without any errors or warnings
- [ ] The code does not contain commented out code
- [ ] The code does not log anything to console
- [ ] I have added unit test(s) to cover new code and successfully executed ran it
- [ ] I have thoroughly tested the new code and any adjacent features it may affect

### Link to related issue(s)

...

### Screenshots or videos (before and after if appropriate)

### FIGMA

![Screen Shot 2022-02-17 at 17 58 46](https://user-images.githubusercontent.com/74447557/154466924-58ab2827-db55-42ba-b799-8e1c2367459e.png)
![Screen Shot 2022-02-17 at 17 58 58](https://user-images.githubusercontent.com/74447557/154466953-1e06a471-1248-4078-8c59-a6dad35c9c5b.png)

Storybook
...

https://user-images.githubusercontent.com/74447557/154467858-385ab87f-24c1-4c00-ab3f-b0998e84c513.mp4

2022-02-17 11:46 UTC, ardiwine requested changes

2022-02-17 11:46 UTC, ardiwine commented on src/Components/Molecules/FMCard/FMCard.interfaces.tsx
> +  isCollapseAble?: boolean;
isCollapsible

2022-02-17 11:46 UTC, ardiwine commented on src/Components/Molecules/FMCard/index.tsx
> +    isCollapseAble,
isCollapsible

2022-02-17 12:00 UTC, bryantobing12 commented on src/Components/Molecules/FMCard/index.tsx
> +import { Box, Collapse } from "@mui/material";
import nya kalau boleh di update farhan. `Box` dari `@mui/material/box`, `collapse` juga sama dan dinaikin keatas sesuai order.

2022-02-17 12:08 UTC, bryantobing12 commented on src/Components/Molecules/FMCard/index.tsx
> +              justifyContent: "space-between",
tambahin `align-items`  center biar title dan icon nya sejajar

2022-02-17 12:09 UTC, bryantobing12 commented on src/Components/Molecules/FMCard/index.tsx
> +                <FAIcon
kayaknya better pake button icon biar bisa navigasi dari keyboard untuk a11y

2022-02-17 12:20 UTC, bryantobing12 commented on src/Components/Molecules/FMCard/index.tsx
> +                  style={{ cursor: "pointer" }}
kalau bisa `sx` lebih bagus daripada inline style. tapi kalau diganti jadi button ga perlu cursor pointer lagi

2022-02-17 12:23 UTC, bryantobing12 commented on src/Components/Molecules/FMCard/index.tsx
> +            {isCollapsible && (
```suggestion
{isCollapsible && (
      <FAIconButton
        testID="icon-button-arrow-collapse"
        onClick={() => {
          setIsOpen(!isOpen);
        }}
      >
        <FAIcon testID="icon-arrow-collapse">arrow_drop_down</FAIcon>
      </FAIconButton>
)}
```

2022-02-17 12:25 UTC, muhammad-farhan64 commented on src/Components/Molecules/FMCard/index.tsx
> +                  style={{ cursor: "pointer" }}
oh oke

2022-02-17 12:34 UTC, bryantobing12 approved these changes

2022-02-17 12:36 UTC, bryantobing12 approved these changes

2022-02-18 04:24 UTC, didikmulyadi approved these changes

2022-02-18 05:58 UTC, merged