552/molecules fm date picker
HZN-one/flex pull request #92
Opened 2022-03-22 04:02 UTC by bryantobing12

## Thanks for your support to the project. Please check below mentioned points -

### Detailed description of changes

- Adding `FMDatePicker` component
- Adding `FMDatePicker` story
- Adding `FMDatePicker` test

### Recommendations on how to test the changes

`yarn storybook`

- Check if the component matches the design

### Checklist for developer

- [x] The code builds clean without any errors or warnings
- [x] The code does not contain commented out code
- [x] The code does not log anything to console
- [x] I have added unit test(s) to cover new code and successfully executed ran it
- [x] I have thoroughly tested the new code and any adjacent features it may affect

### Link to related issue(s)

https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/552

### Screenshots or videos (before and after if appropriate)

#### Before

N / A

#### After

...

2022-03-22 08:57 UTC, gilangdarmawan requested changes

2022-03-22 08:57 UTC, gilangdarmawan commented on src/Components/Molecules/FMDatePicker/index.tsx
> +      <LocalizationProvider dateAdapter={AdapterDateFns}>
How about moving `<LocalizationProvider />` to ThemeWrapperProvider?

2022-03-22 08:57 UTC, gilangdarmawan commented on src/Components/Molecules/index.tsx
> +export * from "./FMDatePicker";
better sort it alphabetically

2022-03-22 08:57 UTC, gilangdarmawan commented on test/Components/Molecules/FMDatePicker/FMDatePicker.test.tsx
> +        value={new Date()}
The date must be static so it will match to snapshot everytime

2022-03-22 11:26 UTC, bryantobing12 commented
@gilangdarmawan updated. Kindly check again. Thanks

2022-03-23 01:11 UTC, gilangdarmawan approved these changes

2022-03-23 01:14 UTC, merged